---
- name: "Apache installation using docker"
  hosts: prod
  become: true
  tasks:
  - name: Create Apache conteneur
    docker_container:
      name: webapp
      image: httpd
      ports:
        - "80:80"
